# -*- coding: utf-8 -*-
"""AutomatedDataAnalysisTeam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VGzhSN67TLFqTNIgrF_41U1MXrhATTLl
"""

!pip install crewai_tools > /dev/null

import os

os.environ["CREWAI_NO_WIDGETS"] = "1"
os.environ["SERPER_API_KEY"] = "YOUR_API_KEY"
os.environ["OPENAI_API_KEY"] = "YOUR_API_KEY"
os.environ["OPENAI_MODEL_NAME"] = "gpt-3.5-turbo"

from crewai import Agent, Task, Crew, Process
from crewai_tools import SerperDevTool

data_collector = Agent(
    role='Data Collector',
    goal='Gather relevant data from various sources. And organize them in a structured manner for beter analysis, query-response, and retrieval.',
    backstory='Experienced in collecting data from various sources.',
    verbose=True,
    tools=[SerperDevTool()]

)

data_analyst = Agent(
    role='Data Analyst',
    goal='Analyze collected data to extract insights. Understand the pattern of the data, and predict any future queries if relevant to the data\'s topic and asked by the user to do so.',
    backstory='Proficient in data analysis and interpretation.',
    verbose=True
)

topic = "Recent Gold Rate Trends"
collect_data_task = Task(
    description=f'Collect data on the specified topic. Topic:{topic}',
    agent=data_collector,
    expected_output='Raw data collected from various sources. Structured in a good manner in points.'
)

analyze_data_task = Task(
    description='Analyze the collected data to extract meaningful insights. And predict the Gold Rates for the next 6 months.',
    agent=data_analyst,
    expected_output='Insights derived from the data analysis. And the next 6 month prediction',
    context=[collect_data_task]
)

data_analysis_crew = Crew(
    agents=[data_collector, data_analyst],
    tasks=[collect_data_task, analyze_data_task],
    process=Process.sequential,
    verbose=True
)

result=data_analysis_crew.kickoff()

with open("GoldRateAnalysis.txt", "w") as f:
    f.write(result.raw)

with open("GoldRateAnalysis.txt", "r") as f:
    print(f.read())